import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ThemeProvider } from "./_context/ThemeContext";
import { AuthProvider } from "./_context/AuthContext";
import { BlogProvider } from "./_context/BlogContext";
import Footer from "./_components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            <BlogProvider>
              <Navbar />
              {children}
              <Footer/>
              </BlogProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
